package com.accioneselbosque.audit.model;

public enum AuditEventType {
    AUTH_SUCCESS, AUTH_FAILURE, AUTH_MFA_FAILED, ACCOUNT_LOCKED, ACCOUNT_UNLOCKED,
    ORDER_CREATED, ORDER_CANCELLED, ORDER_EXECUTED, ORDER_REJECTED,
    PROFILE_UPDATED, PASSWORD_CHANGED,
    SUBSCRIPTION_ACTIVATED, SUBSCRIPTION_EXPIRED,
    USER_SUSPENDED, USER_UNSUSPENDED, ROLE_CHANGED, PARAMETER_CHANGED,
    ADMIN_INITIATED_PASSWORD_RESET,
    PRICE_ALERT_CREATED, PRICE_ALERT_TRIGGERED
}
