ALTER TABLE investor ADD COLUMN IF NOT EXISTS failed_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE investor ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP NULL;
ALTER TABLE investor ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(64) NULL;
